### ISSUE TITLE
Why do neo4j associations take so long to create?

### ISSUE THREAD

**Issue by M-C-Mc** [TransparencyToolkit/Harvester#21]
The cypher queries to create associations and items in neo4j take alarmingly long. Why and how can they be sped up?

**Comment by bnvk** [comment]
Yah! I've noticed this as well. Even for just a 5 MB JSON file, it took like 20 mins and I ultimately killed it as I thought it stalled out! Oddly, neo4j was using very little RAM or CPU

**Comment by bnvk** [comment]
Actually, i'm noticing really weird behavior on this. I ran a report that returned 0 results on Indeed, and it just hung for 20 mins. I manually closed the browser tab that had the Harvester terms form, but now loading any routes of Harvester just hang.
