### ISSUE TITLE
Add authentication to post requests to LookingGlass

### ISSUE THREAD

**Issue by M-C-Mc** [TransparencyToolkit/Harvester#27]
Add some sort of authentication to post requests to LookingGlass

**Comment by bnvk** [comment]
Interesting. Would love to discuss the use cases and implementation ideas. The first thing that comes to mind is making LookingGlass an [oAuth 2](http://oauth.net/2/) provider, however might not be best approach. I wonder if something interesting could be done with PGP...

**Comment by M-C-Mc** [comment]
Probably a simpler solution like an api key. Or check if it is running
not in production.

On 03/29/2016 07:46 PM, Brennan Novak wrote:

> Interesting. Would love to discuss the use cases and implementation
> ideas. The first thing that comes to mind is making LookingGlass an
> oAuth 2 http://oauth.net/2/, however might not be best approach. I
> wonder if something interesting could be done with PGP...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/TransparencyToolkit/Harvester/issues/27#issuecomment-203069308

## 

M. C. McGrath
Transparency Toolkit | http://transparencytoolkit.org

**Comment by M-C-Mc** [comment]
This is just so Harvester can access it- no users or anything yet

On 03/29/2016 07:46 PM, Brennan Novak wrote:

> Interesting. Would love to discuss the use cases and implementation
> ideas. The first thing that comes to mind is making LookingGlass an
> oAuth 2 http://oauth.net/2/, however might not be best approach. I
> wonder if something interesting could be done with PGP...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/TransparencyToolkit/Harvester/issues/27#issuecomment-203069308

## 

M. C. McGrath
Transparency Toolkit | http://transparencytoolkit.org
