### ISSUE TITLE
Implement overview of "collected datasets" view

### ISSUE THREAD

**Issue by bnvk** [TransparencyToolkit/Harvester#6]
An instance of Harvester may be used to collect lots of different datasets / search terms. There needs to be an overview interface of all these datasets!

Here is a wireframe of what this could / should probably look like:

![harvester-collected-data-overview](https://cloud.githubusercontent.com/assets/48677/12587968/ce4b00ca-c456-11e5-8812-b5d0765a0bcc.jpg)

**Comment by M-C-Mc** [comment]
I just noticed that there's currently a LookingGlass button for each dataset. Not sure if this will be in the final version, but there should only be one LookingGlass button (same one for all the datasets) with the spec we discussed today and in January.

**Comment by bnvk** [comment]
Yah, that (repeating LG button) was an oversight, it's fixed on my current local dev! Thanks for clarifying!~
